#################################################################################
# Copyright (c) 2023 T-Systems International GmbH
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
################################################################################
name:  SDE Lint and Test Charts

on:
    push:
      branches:
       - main
      paths:
       - 'charts/**'

    pull_request:
      paths:
       - charts/** 
       
    workflow_dispatch:
      inputs:
        node_image:
          description: 'kindest/node image for k8s kind cluster'
          # k8s version from 3.2 release as default
          default: 'kindest/node:v1.24.6'
          required: false
          type: string
        upgrade_from:
          description: 'chart version to upgrade from'
          # chart version from 3.2 release as default
          default: '0.0.9'
          required: false
          type: string

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.3

      # Setup python as a prerequisite for chart linting 
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "CHART_CHANGED=true" >> $GITHUB_ENV
          fi

      # run chart linting 
      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --config charts/chart-testing-config.yaml

      # Preparing a kind cluster to install and test charts on
      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: ${{ env.CHART_CHANGED == 'true' }}

      # install the chart to the kind cluster and run helm test
      # define charts to test with the --charts parameter
      - name: Run chart-testing (install)
        run: ct install --charts charts/simpledataexchanger --config charts/chart-testing-config.yaml
        if: ${{ env.CHART_CHANGED == 'true' }}

      - name: Run helm install and dependency update
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami          
          helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
          helm dependency update charts/simpledataexchanger 
          helm install simpledataexchanger charts/simpledataexchanger --namespace install --create-namespace
        if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'
        
      - name: Run helm upgrade
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add tractusx-dev https://eclipse-tractusx.github.io/charts/dev
          helm install simpledataexchanger tractusx-dev/sde --version ${{ github.event.inputs.upgrade_from || '0.0.9' }} --namespace upgrade --create-namespace
          helm dependency update charts/simpledataexchanger
          helm upgrade simpledataexchanger charts/simpledataexchanger --namespace upgrade
        if: github.event_name != 'pull_request' || steps.list-changed.outputs.changed == 'true'
